### ISSUE TITLE
Delete DotPay API

### ISSUE THREAD

**Issue by deestt** [PatryQHyper/polish_payments_api#5]
https://www.przelewy24.pl/aktualnosci/kolejny-etap-integracji-przelewy24-i-dotpay-zakonczenie-kwestii-formalnych - połączenie Przelewy24 i DotPay

**Comment by PatryQHyper** [comment]
Połączenie Przelewy24 i DotPay nie znaczy, że bramka dotpaya przestała działać. Bramka DotPaya kieruje teraz na bramkę p24, ale API dla sklepów zostało to samo.
